//
//Copyright (C) 2024 Nordix Foundation.
//For a full list of individual contributors, please see the commit history.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: pkg/proto/translator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventTranslator_TranslateEvent_FullMethodName = "/proto.EventTranslator/TranslateEvent"
)

// EventTranslatorClient is the client API for EventTranslator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventTranslatorClient interface {
	TranslateEvent(ctx context.Context, in *TranslateEventRequest, opts ...grpc.CallOption) (*TranslateEventResponse, error)
}

type eventTranslatorClient struct {
	cc grpc.ClientConnInterface
}

func NewEventTranslatorClient(cc grpc.ClientConnInterface) EventTranslatorClient {
	return &eventTranslatorClient{cc}
}

func (c *eventTranslatorClient) TranslateEvent(ctx context.Context, in *TranslateEventRequest, opts ...grpc.CallOption) (*TranslateEventResponse, error) {
	out := new(TranslateEventResponse)
	err := c.cc.Invoke(ctx, EventTranslator_TranslateEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventTranslatorServer is the server API for EventTranslator service.
// All implementations should embed UnimplementedEventTranslatorServer
// for forward compatibility
type EventTranslatorServer interface {
	TranslateEvent(context.Context, *TranslateEventRequest) (*TranslateEventResponse, error)
}

// UnimplementedEventTranslatorServer should be embedded to have forward compatible implementations.
type UnimplementedEventTranslatorServer struct {
}

func (UnimplementedEventTranslatorServer) TranslateEvent(context.Context, *TranslateEventRequest) (*TranslateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranslateEvent not implemented")
}

// UnsafeEventTranslatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventTranslatorServer will
// result in compilation errors.
type UnsafeEventTranslatorServer interface {
	mustEmbedUnimplementedEventTranslatorServer()
}

func RegisterEventTranslatorServer(s grpc.ServiceRegistrar, srv EventTranslatorServer) {
	s.RegisterService(&EventTranslator_ServiceDesc, srv)
}

func _EventTranslator_TranslateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranslateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventTranslatorServer).TranslateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventTranslator_TranslateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventTranslatorServer).TranslateEvent(ctx, req.(*TranslateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventTranslator_ServiceDesc is the grpc.ServiceDesc for EventTranslator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventTranslator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EventTranslator",
	HandlerType: (*EventTranslatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TranslateEvent",
			Handler:    _EventTranslator_TranslateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/translator.proto",
}
